### ISSUE TITLE
class GDALOpenInfo has no member named papszOpenOptions

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/meteosatlib#7]
only with gdal 1.10 (on f20), working with gdal 2.0 (on f24)

should this be problematic we _could_ drop support for gdal < 2.0 starting from meteosatlib 1.8, but I'd prefer mantain backward compatibility if it's possible

```
libtool: compile:  g++ -DHAVE_CONFIG_H -I.. -I.. -Werror -I/usr/include/gdal -I/usr/include/gdal -I/usr/include/gdal -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -Wall -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -std=c++11 -c reflectance/pixeltolatlon.cpp  -fPIC -DPIC -o reflectance/.libs/libmsatdrv_la-pixeltolatlon.o
libtool: compile:  g++ -DHAVE_CONFIG_H -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -Wall -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -std=c++11 -c msatgdalplugin.cpp -o msatgdalplugin.o >/dev/null 2>&1
utils.cpp: In function 'GDALDataset* msat::gdal::add_extras(GDALDataset*, GDALOpenInfo*)':
utils.cpp:17:33: error: 'class GDALOpenInfo' has no member named 'papszOpenOptions'
     int idx = CSLFindName(info->papszOpenOptions, "MSAT_COMPUTE");
                                 ^
utils.cpp:19:45: error: 'class GDALOpenInfo' has no member named 'papszOpenOptions'
     std::string val(CPLParseNameValue(info->papszOpenOptions[idx], nullptr));
                                             ^
make[2]: *** [libmsatdrv_la-utils.lo] Error 1
```

**Comment by spanezz** [comment]
Closing as duplicate of #6
